<?php

namespace Database\Seeders;

use App\Models\Client;
use Carbon\Carbon;
use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                "name" => "Healthcare Center-RAK",
                "slug_name" => "Healthcare_Center-RAK",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "Ministry Of Infrastructure",
                "start" => "23-10-2017",
                "end" => "14-02-2019",
                "cost" => 14200000,
                "video" => null,
                "client_id" => Client::where('name' , 'Ministry of Health')->first()->id,
                "sector_id" => 3,
            ],
            [
                "name" => "Civil Defense Centre",
                "slug_name" => "Civil_Defense_Centre",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "Ministry Of Infrastructure",
                "start" => null,
                "end" => "26-03-2020",
                "cost" => 12900000,
                "video" => null,
                "client_id" => Client::where('name' , 'Ministry of Interior')->first()->id,
                "sector_id" => 6,
            ],
            [
                "name" => "National Housing",
                "slug_name" => "National_Housing",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "Ministry of Public Works",
                "start" => "16-07-2013",
                "end" => "03-09-2014",
                "cost" => null,
                "video" => null,
                "client_id" => Client::where('name' , 'Ministry of Public Works')->first()->id,
                "sector_id" => 3,
            ],
            [
                "name" => "46 Villas",
                "slug_name" => "46_Villas",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "MINISTTRY OF INFRASTRUCURE",
                "video" => null,
                "cost" => null,
                "start" => null,
                "end" => null,
                "client_id" => Client::where('name' , 'MINISTTRY OF INFRASTRUCURE')->first()->id,
                "sector_id" => 3,
            ],
            [
                "name" => "EQUESTRIAN STABLES & CAMEL CLUB",
                "slug_name" => "EQUESTRIAN_STABLES_&_CAMEL_CLUB",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "AL BONIAN",
                "end" => "01-1-2013",
                "video" => null,
                "cost" => null,
                "start" => null,
                "client_id" => Client::where('name' , 'BANYAN TREE')->first()->id,
                "sector_id" => 4,
            ],
            [
                "name" => "Hotel",
                "slug_name" => "Hotel",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "AL BONIAN",
                "end" => "01-08-2013",
                "video" => null,
                "cost" => null,
                "start" => null,
                "client_id" => Client::where('name' , 'Bab Al Bahar')->first()->id,
                "sector_id" => 3,
            ],
            [
                "name" => "Wedding Hall – Adhan - RAK",
                "slug_name" => "Wedding_Hall_–_Adhan_-_RAK",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, humour and the like.",
                "consultant" => "Al Ain Counsulting Engineers",
                "end" => "30-10-2013",
                "video" => null,
                "cost" => null,
                "start" => null,
                "client_id" => Client::where('name' , 'Crown Prince Court')->first()->id,
                "sector_id" => 6,
            ],
            [
                "name" => "Streit FACTORY",
                "slug_name" => "Streit_FACTORY",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "A number of new facilities were inaugurated, including one of the largest showrooms in the Middle East, the STREIT marine division, Steel Service Solutions, Nano Fire Protection Technology (NFPT), Shooting Lab, Advance Integrated Technologies, and SSV.",
                "consultant" => "Home of Architecture",
                "start" => "15-12-2020",
                "end" => "28-12-2022",
                "video" => null,
                "cost" => 120000000,
                "client_id" => Client::where('name' , 'Streit Group')->first()->id,
                "sector_id" => 1,
            ],
            [
                "name" => "Rakez Warehouses",
                "slug_name" => "Rakez_Warehouses",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "A number of new facilities were inaugurated, including one of the largest showrooms in the Middle East, the STREIT marine division, Steel Service Solutions, Nano Fire Protection Technology (NFPT), Shooting Lab, Advance Integrated Technologies, and SSV.",
                "consultant" => "Al Gurg Consultants",
                "start" => "20-10-2020",
                "end" => "19-12-2022",
                "video" => null,
                "cost" => 75000000,
                "client_id" => Client::where('name' , 'RAK Economic Zone')->first()->id,
                "sector_id" => 1,
            ],
            [
                "name" => "Al Ghurair Aluminum Factory",
                "slug_name" => "Al_Ghurair_Aluminum_Factory",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "A number of new facilities were inaugurated, including one of the largest showrooms in the Middle East, the STREIT marine division, Steel Service Solutions, Nano Fire Protection Technology (NFPT), Shooting Lab, Advance Integrated Technologies, and SSV.",
                "consultant" => "Middle east consultant",
                "end" => "19-04-2023",
                "video" => null,
                "cost" => 15000000,
                "client_id" => Client::where('name' , 'AG Aluminum')->first()->id,
                "sector_id" => 1,
                "start" => null,
            ],
            [
                "name" => "UTICO DESLINATION PLANT",
                "slug_name" => "UTICO_DESLINATION_PLANT",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "A number of new facilities were inaugurated, including one of the largest showrooms in the Middle East, the STREIT marine division, Steel Service Solutions, Nano Fire Protection Technology (NFPT), Shooting Lab, Advance Integrated Technologies, and SSV.",
                "consultant" => "ANT ENGINEERING CONSULTANTS & ALHAMRA ENGINEERING CONSULTANTS",
                "end" => "30-07-2021",
                "video" => null,
                "cost" => 48000000,
                "client_id" => Client::where('name' , 'UTICO')->first()->id,
                "sector_id" => 1,
                "start" => null,
            ],
            [
                "name" => "AL NAKHEEL PAPERMILL",
                "slug_name" => "AL_NAKHEEL_PAPERMILL",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Al Nakheel Hygienic Papermill Factory with Total Built-Up Area 75,000 m2 considering the highest performance requirement for tissues manufacturing – Turnkey Project and full MEP scope with Firefighting Total Project Value : 120 Million Dirhams",
                "consultant" => "COENGER CONSULTANCY",
                "end" => "19-02-2020",
                "video" => null,
                "cost" => 120000000,
                "client_id" => Client::where('name' , 'FINE')->first()->id,
                "sector_id" => 1,
                "start" => '20-10-2018',
            ],
            [
                "name" => "iPack Aseptic Packging",
                "slug_name" => "iPack_Aseptic_Packging",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Al Nakheel Hygienic Papermill Factory with Total Built-Up Area 75,000 m2 considering the highest performance requirement for tissues manufacturing – Turnkey Project and full MEP scope with Firefighting Total Project Value : 120 Million Dirhams",
                "consultant" => "Sacre Davet",
                "end" => "10-08-2019",
                "video" => null,
                "cost" => 50000000,
                "client_id" => Client::where('name' , 'iPack')->first()->id,
                "sector_id" => 1,
                "start" => '20-09-2017',
            ],
            [
                "name" => "Fence International",
                "slug_name" => "Fence_International",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Al Nakheel Hygienic Papermill Factory with Total Built-Up Area 75,000 m2 considering the highest performance requirement for tissues manufacturing – Turnkey Project and full MEP scope with Firefighting Total Project Value : 120 Million Dirhams",
                "consultant" => "Sacre Davey",
                "start" => null,
                "video" => null,
                "cost" => 17000000,
                "client_id" => Client::where('name' , 'Fence International')->first()->id,
                "sector_id" => 1,
                "end" => '10-07-2019',
            ],
            [
                "name" => "INEGRA CEMENT FACTORY",
                "slug_name" => "INEGRA_CEMENT_FACTORY",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Capital Engineering Consultants",
                "start" => '20-12-2018',
                "video" => null,
                "cost" => 56000000,
                "client_id" => Client::where('name' , 'INEGRA')->first()->id,
                "sector_id" => 6,
                "end" => '26-08-2020',
            ],
            [
                "name" => "Air Liquid - Plant, factory and storage sheds",
                "slug_name" => "Air_Liquid_-_Plant,_factory_and_storage_sheds",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Home Of Architecture",
                "start" => '01-04-2018',
                "video" => null,
                "cost" => 100000000,
                "client_id" => Client::where('name' , 'UTICO')->first()->id,
                "sector_id" => 1,
                "end" => '05-10-2021',
            ],
            [
                "name" => "AHMED TEA (London)",
                "slug_name" => "AHMED_TEA_(London)",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Home Of Architecture",
                "start" => null,
                "video" => null,
                "cost" => 100000000,
                "client_id" => Client::where('name' , 'AHMED TEA')->first()->id,
                "sector_id" => 6,
                "end" => '11-11-2011',
            ],
            [
                "name" => "Dual Carriageway and Golf Area",
                "slug_name" => "Dual_Carriageway_and_Golf_Area",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Home Of Architecture",
                "start" => null,
                "video" => null,
                "cost" => 100000000,
                "client_id" => Client::where('name' , 'ALHAMRA')->first()->id,
                "sector_id" => 6,
                "end" => '11-11-2011',
            ],
            [
                "name" => "Etihad Rail",
                "slug_name" => "Etihad_Rail",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Home Of Architecture",
                "start" => '16-11-2020',
                "video" => null,
                "cost" => 36649700,
                "client_id" => Client::where('name' , 'Etihad Railway')->first()->id,
                "sector_id" => 5,
                "end" => '11-02-2022',
            ],
            [
                "name" => "Etihad Rail Roads and Infrastructure Works",
                "slug_name" => "Etihad_Rail_Roads_and_Infrastructure_Works",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => "Jacobs",
                "start" => '16-11-2020',
                "video" => null,
                "cost" => 71000000,
                "client_id" => Client::where('name' , 'Etihad Railway')->first()->id,
                "sector_id" => 5,
                "end" => null,
            ],
            [
                "name" => "Al Mairid Ras Al Khaimah",
                "slug_name" => "Al_Mairid_Ras_Al_Khaimah",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => null,
                "start" => '22-12-2022',
                "video" => null,
                "cost" => 21500000,
                "client_id" => Client::where('name' , 'MARJAN')->first()->id,
                "sector_id" => 5,
                "end" => '08-08-2023',
            ],
            [
                "name" => "Heritage village Ras Al Khaimah",
                "slug_name" => "Heritage_village_Ras_Al_Khaimah",
                "status" => "completed",
                "main_image" => "main.webp",
                "mini_desc" => "Tincidunt elit magnis nulla facilisis sagittis sapien nunc amet ultrices dolores sit ipsum velit purus aliquet massa fringilla leo orci. Sapien nunc amet ultrices, dolores sit ipsum velit massa fringilla leo orci dolors sit amet elit amet.",
                "full_desc" => "Integra Cement Factory is targeting to enter the industry of providing comprehensive cement products in UAE market  through their new factory located in Al Ghail Industrial Area – Ras Al Khaimah – UAE",
                "consultant" => null,
                "start" => '05-01-2023',
                "video" => null,
                "cost" => 19500000,
                "client_id" => Client::where('name' , 'MARJAN')->first()->id,
                "sector_id" => 5,
                "end" => '28-08-2023',
            ],
        ];

        foreach ($data as $key => $value) {
            Project::create([
                'name' => $value['name'],
                'slug_name' => $value['slug_name'],
                'status' => $value['status'],
                'main_image' => $value['main_image'],
                'mini_desc' => $value['mini_desc'],
                'full_desc' => $value['full_desc'],
                'consultant' => $value['consultant'],
                'start' => !empty($value['start']) ?  Carbon::createFromFormat('d-m-Y', $value['start'])->format('Y-m-d H:i:s') : null,
                'end' => !empty($value['end']) ?  Carbon::createFromFormat('d-m-Y', $value['end'])->format('Y-m-d H:i:s')  : null,
                'cost' => $value['cost'],
                'video' => $value['video'],
                'client_id' => $value['client_id'],
                'sector_id' => $value['sector_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
